name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Update package lists
      run: sudo apt-get update
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker.io -y
    - name: Build Docker image
      run: docker build -t learn-asp-action .
    - name: Push Docker image
      run: |
        docker login docker.io -u juleancode -p ${{ secrets.password }}
        docker push learn-asp-action
